config/routes.rb
Rails.application.routes.draw do
  resources :service
  resources :worker
  resources :comment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, :mark, presence: true
  validates :mark, inclusion:1..5
end

app/models/klient.rb
class Klient < ApplicationRecord
  validates :first_name, :last_name, :s_passport, :n_passport, presence: true
  validates :s_passport, inclusion: 1000..9999
  validates :n_passport, inclusion: 100000..999999
  has_many :realties
  has_many :services
end

app/models/realty.rb
class Realty < ApplicationRecord
  validates :kadastr_passport, presence: true
  validates :estimated_cost, numericality: {greater_than: 0}
  enum kind: [:land_plot, :house, :garage, :commerical_realty, :room]
end

app/models/service.rb
class Service < ApplicationRecord
  validates :price, numericality: {greater_than: 0}
  validates :kind, presence: true
end

app/models/worker.rb
class Worker < ApplicationRecord
  validates :first_name, :last_name, presence: true
  has_many :servieces
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
   @comment=Comment.all
  end
end

app/controllers/klient_controller.rb
class KlientController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def show

  end
end

app/controllers/worker_controller.rb
class WorkerController < ApplicationController
  def index
    @workers=Worker.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/klient_helper.rb
module KlientHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/worker_helper.rb
module WorkerHelper
end

app/views/comment/index.html.erb
<% @comment.each do |c|%>
  <%if c.worker_id = :id %>
        <%=c.text%><br>
  <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=image_tag("backP.jpg")%>
    <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == '' %>"><a href="/">Главная</a></li>
      <li class="<%= 'active' if params[:controller] == 'service' %>"><a href="/service">Услуги</a></li>
      <li class="<%= 'active' if params[:controller] == 'klient' %>"><a href="/klient">Клиент</a></li>
      <li class="<%= 'active' if params[:controller] == '' %>"><a href="/">О компании</a></li>
      <li class="<%= 'active' if params[:controller] == '' %>"><a href="/">Контакты</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Зрегистироваться</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
    </ul>
  </nav>
    <%= yield %>

  </body>
</html>

app/views/worker/index.html.erb
<table>
  <% @workers.each do |w|%>
      <tr>
        <td>
          <%= w.first_name%>
        </td>
        <td>
          <%= w.last_name%>
        </td>
        <td>
          <%= w.phone_number%>
        </td>
        <td>
          <%=button_to('Оставить отзыв',comment_index_path,method: :get, id: w.id) %>
        </td>
      </tr>

<%end%>
</table>